# Simple Template to Perform ETL
import os
import itertools

from src.extract.read_log_files import read_log_files

watch_directory = "./sensor_log"
failed_files = []

def run_etl_pipeline():
    """Perform Basic ETL 
    
    Data Source : logs files inside a folder is Auto Generated by another Program
    Data Format : log file is in Json Format contain field 'temp', 'humid', 'dateCreated'
    Data Storage : Data Storage another Folder where each data is summarize into hourly summary
    Assume that in the folder './sensor_log', another program create a log file there in a specific format
    """
    global watch_directory, failed_files

    # Step 1 Extract
    available_files = list(itertools.islice(
        (entry.name for entry in os.scandir(watch_directory) if entry.is_file() and entry.name not in failed_files),
        20
    ))
    contents = read_log_files(available_files)

    if not available_files:
        return
    
    # Step 2 Transform

    # Step 3 Load
    
    pass


if __name__ == "__main__":
    run_etl_pipeline()